### ISSUE TITLE
制作者に問い合わせる のメール項目検討 → 反映

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-showcase#10]
すべて必須

* 問い合わせ先名
* 名前
* よみがな
* メールアドレス
* 会社名
* 電話番号
* 問い合わせ内容

問い合わせ先名 について
* 実績の投稿者名の事
* 実績詳細ページからパラメーターをうけとって、フォームを開いた時点で自動入力されている状態。内容変更不可

**Comment by drill-lancer** [comment]
@kurudrive 
メールの内容はともかくとして大体出来上がりました。
確認お願いします。
https://showcase.vektor-inc.co.jp/production-request/

**Comment by kurudrive** [comment]
@drill-lancer ありがとうございます。
実際の利用を想定してメールの内容を自分の思う範囲で必要に応じて調整よろしくお願いいたします。

**Comment by kurudrive** [comment]
↑ 文面などの事です。

**Comment by drill-lancer** [comment]
自分なりに調整しておきました。

**Comment by kurudrive** [comment]
＠drill-lancer
制作依頼 ...の前の段階なので、メールのタイトルの文言は「制作依頼」ではなく「制作に関する問い合わせ」に変更よろしくお願いいたします。

**Comment by kurudrive** [comment]
@drill-lancer 
- [x]  制作者に届くメールは bcc で vk-support にもメールが届くようにしておいてください。

**Comment by drill-lancer** [comment]
@kurudrive 
- 「制作に関する問い合わせ」の件
- 制作者に届くメールの bcc の件

以上実装しました。

**Comment by kurudrive** [comment]
@drill-lancer あーリがとうございまっすー！！
