### ISSUE TITLE
公開までに必要なタスクの洗い出し

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-showcase#14]
デザインで必要なものなどあれば別途依頼もよろしくお願いいたします。

**Comment by drill-lancer** [comment]
個人的に公開までにやるべきことは下記が挙げられます。
- 制作依頼のボタンの調整
- トップページの作成
- 投稿タイプ「投稿」の扱いをどうするか⇒現在はお知らせを想定
- ショーケースの本文欄をどうするか
