### ISSUE TITLE
アーカイブページのカードに ユーザーが依頼受付中かどうかの表記

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-showcase#15]
該当の事例の投稿者が依頼受付中の場合、
画像右上の標準ではカテゴリーが表示される箇所のラベルを「依頼受付中」にする。
ラベルの背景色は #c00

**Comment by drill-lancer** [comment]
@kurudrive 
本番環境に実装しておきました。

**Comment by kurudrive** [comment]
@drill-lancer 確認しました。ありがとうございます。
