### ISSUE TITLE
必要なもの・不要なものを精査してナビゲーションや表示要素（ウィジェットなど）整える

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-showcase#17]
明らかに不要と思われるウィジェットの削除や、
必要なページにたどりやすいようにメニュー構成を調整

必要・不要の判断は厳密である必要はないのでRICKさんの視点でまずは調整してもらえばOKです。

**Comment by drill-lancer** [comment]
@kurudrive 
とりあえず、必要そうなナビゲーションとウィジェットを設置してみました。

**Comment by kurudrive** [comment]
@drill-lancer ありがとうございます。
制作者登録申請ページへのメニュー項目を追加よろしくお願いいたします。

**Comment by drill-lancer** [comment]
制作者登録申請ページのフォームの仕様は決まりました？
それとも適当にフォームと固定ページを作れば OK ですか？

**Comment by drill-lancer** [comment]
@kurudrive 
適当にフォーム＆固定ページを作成してヘッダーメニューに追加しておきました。

**Comment by kurudrive** [comment]
* 担当者名
* 会社名・屋号
* メールアドレス
* 実績サイトURL（テキストエリア）
２つ以上入力してください

**Comment by kurudrive** [comment]
@drill-lancer ↑でよろしくお願いいたします。

**Comment by drill-lancer** [comment]
@kurudrive 
そのようにしておきました。
https://showcase.vektor-inc.co.jp/registration/

**Comment by kurudrive** [comment]
@drill-lancer ごめんなさい。後で編集したので↑に調整よろしくお願いいたします。

**Comment by drill-lancer** [comment]
@kurudrive
そのようにしておきました。
https://showcase.vektor-inc.co.jp/registration/

**Comment by kurudrive** [comment]
ありがとうございます！
フォーム毎になんか余分に改行入ってるの調整よろしくお願いいたします。

**Comment by kurudrive** [comment]
![Uploading form-br-padding.png…]()

**Comment by kurudrive** [comment]
![form-br-padding](https://user-images.githubusercontent.com/3272660/100577675-0c1d0600-3324-11eb-9acc-22c8a8f1829b.png)

**Comment by drill-lancer** [comment]
@kurudrive 
余白を調整しておきました。
