### ISSUE TITLE
投稿者アーカイブページ の上部にその投稿者の Post Author Display のボックスが表示されるように

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-showcase#18]
Post Author Display の「最近の投稿」情報は表示不要
※ 隠しにくかったら Post Author Display 側を改修か、CSSで非表示にするだけでも化

**Comment by drill-lancer** [comment]
@kurudrive 
一応設置はしましたが・・・
アーカイブページで PAD の CSS が読まれていないみたいです。

**Comment by kurudrive** [comment]
oh...確かに single にしかcss読み込まないかも...

**Comment by kurudrive** [comment]
@drill-lancer アーカイブページでもCSS読み込むようにフック等で対応よろしくお願いいたします。
ｍ（＿　＿）ｍ

**Comment by drill-lancer** [comment]
@kurudrive 
PAD 側で対応しますか？
Showcase 側で対応しますか？

**Comment by drill-lancer** [comment]
@kurudrive 
CSS が当たるようになりました。
https://showcase.vektor-inc.co.jp/author/kurudrive/

**Comment by kurudrive** [comment]
ありがとうございました。
