### ISSUE TITLE
トップページ _ 石川社長の熱いメッセージを

### ISSUE THREAD

**Issue by drill-lancer** [vektor-inc/vk-showcase#19]

**Comment by kurudrive** [comment]
うん、気持ちは大変ありがたいけれど、
多分メッセージとかを載せるならプロダクト紹介ページの方になります。
というのはショーケースサイトの主役は実績＆他の制作者だし、
僕が全面に出るとウチの実績かという間違った印象が交じる（ちゃんと見れば他のユーザー作だとわかるが、認知を遅らせる要素となる）ためです。
