### ISSUE TITLE
カスタム分類 テーマ・プラグイン を追加

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-showcase#24]
ラベル名 : テーマ・スキン
スラッグ名 : theme

* Lightning
* Lightning Pro
    * Origin
    * Charm
    * Variety
* Katawara

**Comment by drill-lancer** [comment]
@kurudrive 
タクソノミーの実装＆タームの設定を完了しました。

**Comment by kurudrive** [comment]
@drill-lancer ありがとうございました！
