### ISSUE TITLE
カスタム投稿タイプ 「制作実績（ showcase ）」及びカスタム分類追加

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-showcase#3]
カスタム分類 設定

[  ] サイト種別・機能 site_type
[  ] 担当範囲  In_charge
[  ] 業種 industry

**Comment by drill-lancer** [comment]
@kurudrive 
https://wpdocs.osdn.jp/%E9%96%A2%E6%95%B0%E3%83%AA%E3%83%95%E3%82%A1%E3%83%AC%E3%83%B3%E3%82%B9/register_post_type

register_post_type の supports の値は
 title と custom-fields のみですか？ editor も追加しますか？

**Comment by drill-lancer** [comment]
@kurudrive 
投稿タイプとタクソノミーは追加しました。
https://github.com/vektor-inc/vk-showcase/commit/211a2fed38674e3fb6cbef3ab06d5d83938acfd4

**Comment by kurudrive** [comment]
@drill-lancer 
投稿タイプのラベルは「制作実績」でよろしくお願いいたします。

**Comment by kurudrive** [comment]
| | 表示名 | スラッグ |
|-| ------------- | ------------- |
| 投稿タイプ | 制作実績  | showcase  |
| カスタム分類 | サイト種別・機能  | site_type  |
| カスタム分類 | 担当範囲 | in_charge  |
| カスタム分類 | 業種  | industry  |

**Comment by drill-lancer** [comment]
@kurudrive 
In_charge の最初の文字は 大文字のアイですか？小文字のエルですか？

**Comment by kurudrive** [comment]
小文字の i でよろしくお願いいたします。

**Comment by drill-lancer** [comment]
@kurudrive
翻訳（？）しておきました。

**Comment by kurudrive** [comment]
@drill-lancer ありがとうございます。
このプラグイン自体は海外は想定していないので、今後は英語からの翻訳自体はしなくても問題ありません。
しかしながら、もしかしたらという事もありますので、翻訳関数を経由しつつ日本語で書いておけばOKです。

例)
```
__( '今日はいい天気', 'vk-showcase );
```

翻訳しなければ当然日本語で表示される
しかし、一応翻訳関数を経由しておけば英語にする事になった場合に該当箇所がどこなのか探しやすいため。

**Comment by drill-lancer** [comment]
@kurudrive 
了解しました。今後はそのようにいたします。
