### ISSUE TITLE
実績紹介ページにカスタムフィールド用意＆値を詳細ページに反映

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-showcase#30]
いろいろ考えた結果カスタムフィールド一個で良いっす。

| フィールド名 | フィールドスラッグ | フィールドタイプ |
| ------------- | ------------- | ------------- |
| サイトURL（必須）  | site_url | テキスト |

### 詳細ページ

本文下に

ボタン「このサイトを見る」を設置。

**Comment by drill-lancer** [comment]
@kurudrive
カスタムフィールドの設置＆反映が終わりました。

**Comment by kurudrive** [comment]
@drill-lancer ありがとうございます！以下よろしくお願いいたしますー。

- [x]  ボタンは別ウィンドウで開くようによろしくお願いいたします
- [x]  Post Author Display の前に表示よろしくお願いいたします。
- [x] 「このサイトを見に行く」→「このサイトを見る」
- [x] 「このサイトを見る」の前に(→)アイコンフォント追加
- [x] 「このサイトを見る」の後ろに別ウィンドウで開く事がわかるようにアイコンフォント追加

**Comment by drill-lancer** [comment]
@kurudrive 
変更しておきました。
https://github.com/vektor-inc/vk-showcase/commit/04653501536d0865f70fc360105aa7764c6c7e35
