### ISSUE TITLE
権限制御変更

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-showcase#33]
- [x] カスタムタクソノミーの対象を投稿に切り替え
- [x] 制作者権限をなくす
- [x] カテゴリーとタグを消す
- [x] 既存の投稿済み実績の投稿タイプを投稿に変更
- [x] 投稿タイプ「実績」削除
- [x] 投稿タイプ「お知らせ」

**Comment by drill-lancer** [comment]
@kurudrive 
一連の作業が終わりました。
確認をお願いします。
