### ISSUE TITLE
寄稿者ユーザーの場合に管理メニューの「ツール」「コメント」は削除

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-showcase#35]

**Comment by drill-lancer** [comment]
@kurudrive 
結論からいうと無理そうです。

理由：
5.5.3 までは edit_posts がなくても投稿タイプ専用の権限を与えればその投稿タイプを編集可能でした。

5.6 になってからは、edit_posts 権限を与えずに投稿タイプ専用の権限を与えた場合、
編集画面は開けますが、編集画面でフリーズしてしまいます。

edit_posts 権限を与えるということは、「寄稿者」と同等の権限を与えることになるので「寄稿者」を採用しています。

edit_posts 権限には下記３つが含まれます。

- 投稿タイプ「投稿」の編集権限
- コメントの閲覧（編集・承認は不可）
- ツールへのアクセス（ほぼ何もできない）

参考：
https://wpdocs.osdn.jp/%E3%83%A6%E3%83%BC%E3%82%B6%E3%83%BC%E3%81%AE%E7%A8%AE%E9%A1%9E%E3%81%A8%E6%A8%A9%E9%99%90#.E7.89.B9.E5.88.A5.E3.81.AA.E3.82.B1.E3.83.BC.E3.82.B9

https://www.adminweb.jp/wordpress/user/index5.html#section2

**Comment by drill-lancer** [comment]
ただ、「寄稿者」だと画像のアップロードはできないようなので
read delete_posts edit_posts upload_files の４つを許可した権限を新たに作る必要はありそうです。

**Comment by drill-lancer** [comment]
製作者権限は追加しました。 5fb68f117419d550c92d1fc4d717db75efda8e1c

**Comment by drill-lancer** [comment]
メニュー項目の削除も完了しました。 ba91f5abea3b8f02e124720675d30960737baf4b

**Comment by drill-lancer** [comment]
済んだ話なので Close
