### ISSUE TITLE
フッター部分のロゴ

### ISSUE THREAD

**Issue by junonet** [vektor-inc/vk-showcase#38]
フッター部分のロゴを
透明pngの
https://vws.vektor-inc.co.jp/wp-content/uploads/2020/04/head_logo2020.png
に変えていただきたいです。

**Comment by kurudrive** [comment]
@junonet 
変更しましたーん！
https://showcase.vektor-inc.co.jp/

**Comment by junonet** [comment]
何時まで起きてるんですか、寝てください。
早々の対応、ありがとうございました。
