### ISSUE TITLE
投稿者アーカイブページで投稿者情報がイマイチ反映されてない

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-showcase#39]
![投稿者-Vektor-Themes-Showcase](https://user-images.githubusercontent.com/3272660/124602617-02ecac80-dea4-11eb-8d5a-cbe35bb1dd4c.png)

**Comment by drill-lancer** [comment]
TypeSquare Webfonts for エックスサーバー
上記を無効化したら表示されるようになりました。
