### ISSUE TITLE
ユーザーロール「制作者（creator）」発行

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-showcase#5]
投稿タイプ showcase に寄稿権限

* 投稿の公開権限 : 無
* 公開済みの自分の投稿編集権限 : 有
* 他人の投稿の編集権限 : 無

**Comment by drill-lancer** [comment]
@kurudrive 
購読者 + showcase の寄稿権限 という形で OK ですか？
https://wpdocs.osdn.jp/%E3%83%A6%E3%83%BC%E3%82%B6%E3%83%BC%E3%81%AE%E7%A8%AE%E9%A1%9E%E3%81%A8%E6%A8%A9%E9%99%90#edit_posts

**Comment by kurudrive** [comment]
@drill-lancer はい。概ねそれで良いのではと思います。
公開済みの自分の投稿は編集権限ありでよろしくお願いいたします。

**Comment by kurudrive** [comment]
@drill-lancer でよろしくお願いいたします。
表示名 : 制作者
ロールのスラッグ : creator

**Comment by drill-lancer** [comment]
@kurudrive 
翻訳（？）しておきました。

**Comment by kurudrive** [comment]
ありがとうございましたん！
