### ISSUE TITLE
「この制作者に問い合わせる」ボタンを the_content にフックで追加

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-showcase#8]
対象 : 実績のsingleページ

その制作者（ユーザー）情報で「制作問い合わせをうけつける」にチェックが入っている場合に表示

ボタンをクリックしたら、その投稿者のメールアドレスが送信先になっているフォーム画面を表示。

[  ] 問い合わせ用の固定ページを作成
[  ] 仮の問い合わせフォーム作成（メールアドレス・名前・問い合わせ内容 以外の項目は別途検討するので無しでOK）
[  ] ボタン設置
[  ] 依頼受付チェックが入っていない制作者の場合は「現在この制作者は依頼を受け付けていません」を表示。

**Comment by drill-lancer** [comment]
@kurudrive
ボタン設置についてはページでブロックを使うなら
the_content フックを使わなくても
サーバーサイドレンダリング側にに同梱してしまえば OK かと・・・

**Comment by drill-lancer** [comment]
@kurudrive 
とりあえず、フォーム（仮）と固定ページ（仮）は作成済みです。

**Comment by kurudrive** [comment]
> サーバーサイドレンダリング側にに同梱してしまえば OK かと・・・

ちょっとどういう意味かわからないのですが、もしかしたらショーケース専用のブロックは特に配置しないかもしれないのと、別に配置してあったとしても the_content フックで良いと思うので、とりあえずボタン設置よろしくお願いいたします。

**Comment by drill-lancer** [comment]
@kurudrive 
ボタンの設置は完了しました。
https://github.com/vektor-inc/vk-showcase/commit/456bfb0ee025e71aae7d27a4a4bb2cc6fbd0aa71

**Comment by kurudrive** [comment]
@drill-lancer 確認しました！

**Comment by kurudrive** [comment]
@drill-lancer 
btn-block btn-lg でよろしくお願いいたします。

**Comment by drill-lancer** [comment]
@kurudrive 
「この製作者に制作依頼をする」に btn-block btn-lg を追加しておきました。

**Comment by kurudrive** [comment]
@drill-lancer あざまっす！
